repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        name: "Python: ruff linter"
        args: [--fix]
        types_or: [python, pyi]

      - id: ruff-format
        name: "Python: ruff formatter"
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.0
    hooks:
      - id: clang-format
        name: "C++: clang-format formatter"
        types_or: [c++, c]

  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.2
    hooks:
      - id: cpplint
        name: "C++: cpplint"
        types_or: [c++, c]

  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.2.1.1
    hooks:
      - id: buildifier
        name: "Bazel: buildifier formatter"
        args: [--mode=fix]
        exclude: ^bazel_ros2_rules/lib/private/templates/
        files: \.(bazel|bzl|BUILD)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
