workspace(name = "ros2_example_bazel_installed")

load("//tools:environ.bzl", "environment_repository")
environment_repository(
    name = "ros2_example_bazel_installed_environ",
    envvars = ["ROS2_DISTRO_PREFIX"],
)
load("@ros2_example_bazel_installed_environ//:environ.bzl", "ROS2_DISTRO_PREFIX")

local_repository(
    name = "bazel_ros2_rules",
    path = "../bazel_ros2_rules",
)
load("@bazel_ros2_rules//deps:defs.bzl", "add_bazel_ros2_rules_dependencies")
add_bazel_ros2_rules_dependencies()

load("//tools:ros2.bzl", "ros2_repository")
ros2_repository(
    name = "ros2",
    prefix = ROS2_DISTRO_PREFIX,
    include_packages = [
        "action_msgs",
        "builtin_interfaces",
        "rosidl_default_generators",
        "rclcpp_action",
        "rclcpp",
        "rclpy",
        # RMW implementations
        "rmw_cyclonedds_cpp",
        "rmw_fastrtps_cpp",
    ]
)
