workspace(name = "lint")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("//:drake.bzl", "DRAKE_SUGGESTED_VERSION")

http_archive(
    name = "drake",
    sha256 = DRAKE_SUGGESTED_VERSION.sha256,
    strip_prefix = DRAKE_SUGGESTED_VERSION.strip_prefix,
    urls = [
        DRAKE_SUGGESTED_VERSION.url,
    ],
)

load("@drake//tools/workspace:default.bzl", "add_default_workspace")

add_default_workspace()
