workspace(name = "drake_ros_viz")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_googletest",
    sha256 = "fbc8efdca4238e7dbe0642e29911a77be393f191a2444fa10372ee99bb665125",  # noqa
    strip_prefix = "googletest-1.12.0",
    urls = ["https://github.com/google/googletest/archive/refs/tags/v1.12.0.zip"],  # noqa
)

# Use the ROS 2 bazel rules
local_repository(
    name = "bazel_ros2_rules",
    path = "../bazel_ros2_rules",
)

load("@bazel_ros2_rules//deps:defs.bzl", "add_bazel_ros2_rules_dependencies")

add_bazel_ros2_rules_dependencies()

load("@bazel_ros2_rules//ros2:defs.bzl", "ros2_archive")

# Use ROS 2
ros2_archive(
    name = "ros2",
    include_packages = [
        "geometry_msgs",
        "rclcpp",
        "rclpy",
        "tf2_ros",
        "tf2_ros_py",
        "visualization_msgs",
    ],
    sha256_url = "https://repo.ros2.org/ci_archives/drake-ros-underlay/ros2-humble-linux-focal-amd64-ci-CHECKSUM",  # noqa
    strip_prefix = "ros2-linux",
    url = "http://repo.ros2.org/ci_archives/drake-ros-underlay/ros2-humble-linux-focal-amd64-ci.tar.bz2",  # noqa
)

# Depend on Drake
DRAKE_TAG = "v1.10.0"

DRAKE_CHECKSUM = "78bd251bcfb349c988ee9225175a803a50cc53eaacdeb3bba200dfc82dcea305"  # noqa

http_archive(
    name = "drake",
    sha256 = DRAKE_CHECKSUM,
    strip_prefix = "drake-{}".format(DRAKE_TAG.lstrip("v")),
    urls = [
        "https://github.com/RobotLocomotion/drake/archive/refs/tags/{}.tar.gz".format(DRAKE_TAG),  # noqa
    ],
)

load("@drake//tools/workspace:default.bzl", "add_default_workspace")

add_default_workspace()

local_repository(
    name = "drake_ros_core",
    path = "../drake_ros_core",
)

local_repository(
    name = "drake_ros_tf2",
    path = "../drake_ros_tf2",
)
